### PR TITLE
Goziyev spr23

### PR DESCRIPTION
**Pull request by AmirG2003**

### CODE REVIEW

**Review by petschekr — COMMENTED** [review]
Made a few changes to fix some minor things. If it looks good to you, mark the changes as approved and merge it!

Do you have an uncropped version of the photo of C/House? It's a portrait photo so it looks really big compared to all the other landscape photos on the main page.

**Comment by petschekr** [comment]
Also, https://afrotc.gatech.edu/# is reporting that the website is currently down. Can you look into that when pushing this new version?

**Comment by AmirG2003** [comment]
It is not down from my end. Also, for C/House, no that's the one I was sent. Would you recommend a different image there?

**Comment by AmirG2003** [comment]
Also, we are not opening NSE for Fall 2025 yet. It's supposed to be Fall 2024 even though the semester already started.

**Comment by petschekr** [comment]
Ah yeah the website is back up again now. Probably an issue with GT. If you could ask for a zoomed out or a different photo that would look better in landscape, that would be best. If they can't get you one, no worries. 
image

And the Fall 2025 is for the future interest form. Is that not correct?

**Comment by AmirG2003** [comment]
Cadre are really pushing this update, so I will keep C/House's picture for now, and change it later for something better. As for the NSE, they gave me the one for Fall 2024, so we will keep it that way.

**Review by petschekr — APPROVED** [review]

**Comment by AmirG2003** [comment]
Hey, majority of the changes have passed except the top picture skyline.jpg, do I have to pull another update.

**Comment by AmirG2003** [comment]
It was supposed to change to formation_gmc.jpg

**Comment by petschekr** [comment]
The cache on the GT server sometimes sticks around for quite a while. Try Ctrl-Shift-R in your browser and the new image should pop up

**Comment by AmirG2003** [comment]
It worked, thank you.

**Pull request merged**
