### PR TITLE
Added Enrollment Information Packet_Spring 2023

### PR DESCRIPTION
**Pull request by JonahTS**

### CODE REVIEW

**Review by petschekr — CHANGES_REQUESTED** [review]
Probably want to update the `To enroll for Fall 2023` language in addition to the future interest language in `join.hbs` and `contact.hbs`

**Comment by JonahTS** [comment]
Just pushed another , changed to Spring 2024 for next semester

**Comment by petschekr** [comment]
I updated the future interest links from "Spring 2024" to "Fall 2024" too (just run `git pull`). Last thing is can you update the dates and deadlines?

**Comment by JonahTS** [comment]
I'll ask Capt Spear tomorrow and double check the dates/deadlines

**Pull request closed without merging**
